name: build
on: [push, pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.55.2

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build and push branched image
      if: github.event_name == 'push' && github.ref != 'refs/heads/main'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWD }} | docker login -u ${USERNAME} --password-stdin
        echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-tgbot:${{ github.ref_name }} \
          -t ghcr.io/${USERNAME}/quake3-tgbot:${{ github.ref_name }} .

    - name: build and push latest image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWD }} | docker login -u ${USERNAME} --password-stdin
        echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-tgbot:latest \
          -t ghcr.io/${USERNAME}/quake3-tgbot:latest .

    - name: build and push tagged image
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        USERNAME: ${{ secrets.USERNAME }}
        GITHUB_REF: ${{ github.ref}}
      run: |
        ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
        echo GITHUB_REF - $ref
        echo ${{ secrets.DOCKERHUB_PASSWD }} | docker login -u ${USERNAME} --password-stdin
        echo ${{ secrets.GITPKG_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
        docker buildx build --push --platform linux/amd64,linux/arm64 \
          -t ${USERNAME}/quake3-tgbot:${ref} \
          -t ghcr.io/${USERNAME}/quake3-tgbot:${ref} .